import { Product } from "@models";

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    title: "Wireless Earbuds Pro",
    description: "Premium active noise cancelling earbuds with 30hr battery",
    price: 149.99,
    image: "https://picsum.photos/seed/earbuds/400/400",
    category: "Electronics",
    rating: 4.8,
    reviewCount: 2341,
  },
  {
    id: "p2",
    title: "Smart Watch Ultra",
    description: "Titanium case, GPS, health monitoring & cellular",
    price: 399.99,
    image: "https://picsum.photos/seed/smartwatch/400/400",
    category: "Electronics",
    rating: 4.7,
    reviewCount: 1856,
  },
  {
    id: "p3",
    title: "Leather Crossbody Bag",
    description: "Genuine Italian leather with adjustable strap",
    price: 89.99,
    image: "https://picsum.photos/seed/leatherbag/400/400",
    category: "Fashion",
    rating: 4.5,
    reviewCount: 734,
  },
  {
    id: "p4",
    title: "Minimalist Sneakers",
    description: "Handcrafted premium leather low-top sneakers",
    price: 129.99,
    image: "https://picsum.photos/seed/sneakers/400/400",
    category: "Fashion",
    rating: 4.6,
    reviewCount: 1205,
  },
  {
    id: "p5",
    title: "Titanium Sunglasses",
    description: "Polarized lenses with ultralight titanium frame",
    price: 199.99,
    image: "https://picsum.photos/seed/sunglasses/400/400",
    category: "Accessories",
    rating: 4.4,
    reviewCount: 567,
  },
  {
    id: "p6",
    title: "Portable Charger 20K",
    description: "20000mAh fast-charging power bank with USB-C",
    price: 49.99,
    image: "https://picsum.photos/seed/charger/400/400",
    category: "Electronics",
    rating: 4.3,
    reviewCount: 3102,
  },
  {
    id: "p7",
    title: "Canvas Tote Bag",
    description: "Eco-friendly organic cotton canvas tote",
    price: 34.99,
    image: "https://picsum.photos/seed/totebag/400/400",
    category: "Fashion",
    rating: 4.2,
    reviewCount: 891,
  },
  {
    id: "p8",
    title: "Mechanical Keyboard",
    description: "Wireless mechanical keyboard with RGB backlight",
    price: 169.99,
    image: "https://picsum.photos/seed/keyboard/400/400",
    category: "Electronics",
    rating: 4.9,
    reviewCount: 4230,
  },
  {
    id: "p9",
    title: "Silver Chain Bracelet",
    description: "Sterling silver 925 curb chain bracelet",
    price: 59.99,
    image: "https://picsum.photos/seed/bracelet/400/400",
    category: "Accessories",
    rating: 4.6,
    reviewCount: 423,
  },
  {
    id: "p10",
    title: "Wool Blend Scarf",
    description: "Luxurious merino wool blend winter scarf",
    price: 44.99,
    image: "https://picsum.photos/seed/scarf/400/400",
    category: "Accessories",
    rating: 4.5,
    reviewCount: 612,
  },
];

export const CATEGORIES = ["All", "Electronics", "Fashion", "Accessories"];
